import { Img } from "./Img";
import { Button } from "./Button";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Input } from "./Input";
import { TextArea } from "./TextArea";
import { CheckBox } from "./CheckBox";
import { Slider } from "./Slider";
import { SelectBox } from "./SelectBox";
export { Img, Button, Text, Heading, Input, TextArea, CheckBox, Slider, SelectBox };
